name: Java CI with Maven

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Set up Selenium server container along with Chrome browser
    - name: Set up Selenium
      uses: SeleniumHQ/docker-selenium@v3

    # Add any other necessary setup steps here

    - name: Run API test
      run: mvn clean test -Dsuite=api

    - name: Run Web test
      run: mvn clean test -Dsuite=web
