name: Java CI with Maven

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Install Google Chrome and ChromeDriver for Selenium
    - name: Set up Chrome
      uses: nanasess/setup-chrome@v1

    # Add any other necessary setup steps here

    - name: Run API test
      run: mvn clean test -Dtest=api.xml

    # Add this step to run the web tests using TestNG with Selenium WebDriver
    - name: Run Web test
      run: mvn clean test -Dtest=web.xml
