name: Java CI with Maven
on:
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Start selenoid
      uses: Xotabu4/selenoid-github-action@v2
    - uses: actions/checkout@v1
    - run: npm ci  
    - name: Run Web tests
      env:
        SELENIUM_HUB_HOST: 'localhost'
      run: mvn clean test -Dsuite=web

    - name: Run API test
      run: mvn clean test -Dsuite=api
